### ISSUE TITLE
feat: Make package manager configurable

### ISSUE THREAD

**Issue by tyler36** [julienloizelet/ddev-playwright#12]
I was playing around with this addon this morning and noticed it created a `yarn.lock`.
My project currenly uses NPM and therefore `package-lock.json`.

Using both NPM & YARN in the same project is not recommend and can lead to version conflicts and other hard-to-debug issues over time.

Please consider making the package manager configurable to avoid this issue.

**Comment by julienloizelet** [comment]
Completed by https://github.com/julienloizelet/ddev-playwright/pull/15
