### ISSUE TITLE
Is there a way to run shell commands on the web container, from the playwright one?

### ISSUE THREAD

**Issue by deviantintegral** [julienloizelet/ddev-playwright#22]
Hi @julienloizelet , hope all is well with you.

I wonder if it is time to look at moving either this repo or https://github.com/deviantintegral/ddev-playwright to under the ddev namespace.

In a related topic, I'd like to transfer https://github.com/deviantintegral/playwright-drupal to either the Lullabot or ddev namespaces, and add some colleagues of mine to help maintain it.

I took a look again at the code here (I haven't run it yet), and the one thing I'm not sure is possible is running shell commands on the web container to run test setup steps.

We do a few things in `playwright-drupal` that run commands on the web container:

1. We can run arbitrary [drush commands against a specific test site](https://github.com/deviantintegral/playwright-drupal/tree/main/bin). In tests, we use this to conditionally enable modules and other such things, but just for specific test cases.
2. We also use that to install a base copy of the site with sqlite for tests: https://github.com/deviantintegral/playwright-drupal/blob/main/src/setup/global-setup.ts
3. We also use this to get the right session cookie data so we can run tests in parallel: https://github.com/deviantintegral/playwright-drupal/blob/main/src/testcase/test.ts#L40

Have you encountered a need for anything like this? The only way I can think of to do this with a separate container is to bind the docker socket in to the playwright container, and I'm not sure that would always work in all environments.

cc @rfay .

**Comment by julienloizelet** [comment]
Hi @deviantintegral, thanks for your message.

I'm not a drupal user, but as far as I understand, the `drush` command is a cli tool like `bin/magento` for Magento 2 or `wp` for WordPress.

Most of the time, if I have to run such a cli tool, I run it from the web container. 

In the event that I need to execute a PHP script during a Playwright test, I've found no better way than to create a simple `custom-script.php` that executes PHP code (with `exec` native PHP method or whatever). 
To run the script, I browse to with `await page.goto('/custom-script')` or `await page.goto('/custom-script?action=flushCache&other_action=something_else')`.

It's probably not very clean, but with this type of approach, we can act on the web container.

For information, but I'm not sure it is related to your need,  all the `/var/www/html` code is also available in the playwright container (thanks to this volume:
https://github.com/julienloizelet/ddev-playwright/blob/main/docker-compose.playwright.yaml#L35).

Thanks again !

**Comment by rfay** [comment]
I'm all in favor of consolidated maintenance. Anything that moves to the ddev namespace still needs great maintainers like the two of you. Figuring out the best thing for you as maintainers and for users is the key goal.

**Comment by deviantintegral** [comment]
Thanks for the update, it's appreciated. I'm glad to see there isn't anything we missed.

We aim to avoid writing web-accessible scripts like you've mentioned, as there's been cases in the past where they accidentally get deployed to production and expose sites to serious security issues. The surface area of what you can do with drush is just so large that writing wrappers around it could be pretty complex and time consuming! Running commands directly also lets us more easily stream and route output from stdout and stderr during test execution, without having to bounce through an http request.
